### `参数获取与校验器使用`

```js
const Router = require('koa-router');
const router =  new Router()
router.post('/v1/:id/book',(ctx, next)=>{
  //以下共有四种传参方式：
  const path = ctx.params;//获取id
  const query = ctx.request.query; //获取查询参数
  const headers = ctx.request.header; //获取header
  //获取body，body需要借助koa-bodyparser插件获取(实际上是个中间件)
  const body = ctx.request.body;
  console.log(path,query,headers,body);
  ctx.body = { msg:'success' }
})
module.exports = router
```
### `同步异常处理`
同步异常可以使用try catch去处理，但只用try catch无法捕捉异常
```js
function func1(){
  func2()
}
function func2(){
  try {
    func3()
  } catch (error) {
    console.log('error');
  }
}
function func3(){
  setTimeout(function() {
    throw new Error('chucuole')
  },2000)
}
//并不会打印error，程序在执行func3时直接return了，2秒后才抛出异常
```

### `异步异常处理`
可以通过promise处理
```js
function func1(){
  func2()
}
async function func2(){
  try {
    await func3()
  } catch (error) {
    console.log('error');
  }
}
function func3(){
  return new Promise((resolve,reject)=>{
    setTimeout(function() {
    reject('error')
  },2000)
  })
  
}
```

### `全局异常处理中间件`
在项目目录下创建middlewares文件夹，创建exception.jsw文件做全局处理
```js
//exception.js
//全局异常处理中间件
const catchError = async (ctx, next) => {
  try {
    await next();
  } catch (error) {
    ctx.body = '服务器异常！'
    //message
    //error_code 详细，开发者可自定义 如自定义10001为系统未知异常
    //request_url

    //已知型错误  比如传的数据类型有误
    //未知型错误  程序潜在错误， 无意识，根本不知道他出错了 比如连接数据库
  }
}
module.exports = catchError;
//app.js
const catchError = require('./middlewares/exception');
app.use(catchError)
```

### `定义异常返回格式`
```js
//book.js
const Router = require('koa-router');
const router =  new Router()
router.post('/v1/:id/book',(ctx, next)=>{
  //以下共有四种传参方式：
  const path = ctx.params;//获取id
  const query = ctx.request.query; //获取查询参数
  const headers = ctx.request.header; //获取header
  //获取body，body需要借助koa-bodyparser插件获取(实际上是个中间件)
  const body = ctx.request.body;
  if (JSON.stringify(query)==='{}') {
    const error = new Error('请求参数有误')
    error.code = 10001;
    error.status = 400;
    error.requestUrl = `${ctx.method} ${ctx.path}`
    throw error;
  }
  ctx.body = { msg:'success' }
})

module.exports = router
//expection.js
const catchError = async (ctx, next) => {
  try {
    await next();
  } catch (error) {
    if (error.code) {
      ctx.body = {
        msg: error.message,
        code: error.code,
        request: error.requestUrl
      }
      ctx.status = error.status;
    }
  }
}
module.exports = catchError;
```

### `定义HttpException异常基类`
```js
//上面的异常处理比较麻烦，如果每个都那样写会很麻烦，我们可以再定义一个类去继承
//httpException.js
class HttpException extends Error {
  constructor(msg='服务器异常',errorCode= 1000, code = 400){
    super()
    this.errorCode = errorCode;
    this.code = code;
    this.msg = msg
  }
}
module.exports = HttpException;
//expection.js
const HttpException = require('../core/httpException');
const catchError = async (ctx, next) => {
  try {
    await next();
  } catch (error) {
    if (error instanceof HttpException) {
      ctx.body = {
        msg: error.msg,
        code: error.code,
        request: `${ctx.method} ${ctx.path}`
      }
      ctx.status = error.code;
    }
  }
}
module.exports = catchError;
//book.js
const Router = require('koa-router');
const router =  new Router();
const HttpException = require('../../../core/httpException');
router.post('/v1/:id/book',(ctx, next)=>{
  const path = ctx.params;
  const query = ctx.request.query; 
  const headers = ctx.request.header; 
  const body = ctx.request.body;
  if (JSON.stringify(query)==='{}') {
    const error = new HttpException('请求参数有误',1001,400)
    throw error;
  }
  ctx.body = { msg:'success' }
})
module.exports = router
```

### `特定异常类与全局异常处理`
定义特定异常类：
```js
class HttpException extends Error{
  constructor(msg='服务器异常',errorCode=10000, code=400){
      super()
      this.errorCode = errorCode
      this.code = code
      this.msg = msg
  }
}

class ParameterException extends HttpException{
  constructor(msg, errorCode){
      super()
      this.code = 400
      this.msg = msg || '参数错误'
      this.errorCode = errorCode || 10000
  }
}

class Success extends HttpException{
  constructor(msg, errorCode){
      super()
      this.code = 201
      this.msg = msg || 'ok'
      this.errorCode = errorCode || 0
  }
}

class NotFound extends HttpException{
  constructor(msg, errorCode) {
      super()
      this.msg = msg || '资源未找到'
      this.errorCode = errorCode || 10000
      this.code = 404
  }
}

class AuthFailed  extends HttpException {
  constructor(msg, errorCode) {
      super()
      this.msg = msg || '授权失败'
      this.errorCode = errorCode || 10004
      this.code = 401
  }
}

class Forbbiden extends HttpException{
  constructor(msg, errorCode) {
      super()
      this.msg = msg || '禁止访问'
      this.errorCode = errorCode || 10006
      this.code = 403
  }
}

class LikeError extends HttpException {
  constructor(msg, error_code) {
      super()
      this.code = 400
      this.msg = "你已经点赞过"
      this.error_code = 60001
  }
}

class DislikeError extends HttpException {
  constructor(msg, error_code) {
      super()
      this.code = 400
      this.msg = "你已取消点赞"
      this.error_code = 60002
  }
}

module.exports = {
  HttpException,
  ParameterException,
  Success,
  NotFound,
  AuthFailed,
  Forbbiden,
  LikeError,
  DislikeError
}
```
全局异常处理：
```js
const requireDirectory = require('require-directory');
const Router = require('koa-router');
class InitManager{
  static initCore(app) {
    //入口方法
    InitManager.app = app;
    InitManager.initLoadRouters();
    InitManager.loadHttpException();
  }
  static initLoadRouters(){
    requireDirectory(module, `${process.cwd()}/app/api`,{visit:whenLoadModule});
    function whenLoadModule(obj) {
      if (obj instanceof Router) {
        InitManager.app.use(obj.routes())
      }
    }
  }
  //在init中把异常处理挂载到全局
  static loadHttpException(){
    const errors = require('./httpException');
    global.errs = errors;
  }
}
module.exports = InitManager;
```

